services:
  flutter:
    build: .
    container_name: lookwritelearn_flutter
    working_dir: /app
    volumes:
      - ./:/app
      - flutter_pub_cache:/root/.pub-cache
    # Expose common dev ports (web/servers). Adjust as needed.
    ports:
      - "8080:8080"
      - "3000:3000"
      - "3001:3001"
    command: bash -lc "flutter doctor -v"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: lookwritelearn_backend
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  flutter_pub_cache:

networks:
  app-network:
    driver: bridge


