name: lookwritelearn
description: "LookWriteLearn - handwriting practice app for kids (letters & numbers)"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  provider: ^6.1.2
  google_fonts: ^6.2.1
  http: ^1.1.0
  image: ^4.2.0  # For template matching and SSIM

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  # Using Google Fonts at runtime for freehand guide letters (e.g., Caveat)
  
  # Template assets for offline character recognition
  assets:
    - assets/templates/uppercase/
    - assets/templates/lowercase/
    - assets/templates/numbers/


