name: lookwritelearn
description: "LookWriteLearn - handwriting practice app for kids (letters & numbers)"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  provider: ^6.1.2
  google_fonts: ^6.2.1
  http: ^1.1.0
  image: ^4.2.0  # For template matching and SSIM

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  # Using Google Fonts at runtime for freehand guide letters (e.g., Caveat)
  
  # Template assets for offline character recognition
  assets:
    # Uppercase letters (A-Z)
    - assets/templates/uppercase/A/
    - assets/templates/uppercase/B/
    - assets/templates/uppercase/C/
    - assets/templates/uppercase/D/
    - assets/templates/uppercase/E/
    - assets/templates/uppercase/F/
    - assets/templates/uppercase/G/
    - assets/templates/uppercase/H/
    - assets/templates/uppercase/I/
    - assets/templates/uppercase/J/
    - assets/templates/uppercase/K/
    - assets/templates/uppercase/L/
    - assets/templates/uppercase/M/
    - assets/templates/uppercase/N/
    - assets/templates/uppercase/O/
    - assets/templates/uppercase/P/
    - assets/templates/uppercase/Q/
    - assets/templates/uppercase/R/
    - assets/templates/uppercase/S/
    - assets/templates/uppercase/T/
    - assets/templates/uppercase/U/
    - assets/templates/uppercase/V/
    - assets/templates/uppercase/W/
    - assets/templates/uppercase/X/
    - assets/templates/uppercase/Y/
    - assets/templates/uppercase/Z/
    # Lowercase letters (a-z)
    - assets/templates/lowercase/a/
    - assets/templates/lowercase/b/
    - assets/templates/lowercase/c/
    - assets/templates/lowercase/d/
    - assets/templates/lowercase/e/
    - assets/templates/lowercase/f/
    - assets/templates/lowercase/g/
    - assets/templates/lowercase/h/
    - assets/templates/lowercase/i/
    - assets/templates/lowercase/j/
    - assets/templates/lowercase/k/
    - assets/templates/lowercase/l/
    - assets/templates/lowercase/m/
    - assets/templates/lowercase/n/
    - assets/templates/lowercase/o/
    - assets/templates/lowercase/p/
    - assets/templates/lowercase/q/
    - assets/templates/lowercase/r/
    - assets/templates/lowercase/s/
    - assets/templates/lowercase/t/
    - assets/templates/lowercase/u/
    - assets/templates/lowercase/v/
    - assets/templates/lowercase/w/
    - assets/templates/lowercase/x/
    - assets/templates/lowercase/y/
    - assets/templates/lowercase/z/
    # Numbers (0-9)
    - assets/templates/numbers/0/
    - assets/templates/numbers/1/
    - assets/templates/numbers/2/
    - assets/templates/numbers/3/
    - assets/templates/numbers/4/
    - assets/templates/numbers/5/
    - assets/templates/numbers/6/
    - assets/templates/numbers/7/
    - assets/templates/numbers/8/
    - assets/templates/numbers/9/


